/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateRouteImport } from './routes/create'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as HashtagTagRouteImport } from './routes/hashtag.$tag'
import { Route as MessagesIndexRouteImport } from './routes/messages/index'
import { Route as MessagesConversationIdRouteImport } from './routes/messages/$conversationId'
import { Route as PostPostIdRouteImport } from './routes/post.$postId'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const HashtagTagRoute = HashtagTagRouteImport.update({
  id: '/hashtag/$tag',
  path: '/hashtag/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesConversationIdRoute = MessagesConversationIdRouteImport.update({
  id: '/messages/$conversationId',
  path: '/messages/$conversationId',
  getParentRoute: () => rootRouteImport,
} as any)
const PostPostIdRoute = PostPostIdRouteImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/hashtag/$tag': typeof HashtagTagRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/post/$postId': typeof PostPostIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/messages/': typeof MessagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/hashtag/$tag': typeof HashtagTagRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/post/$postId': typeof PostPostIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/messages': typeof MessagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/hashtag/$tag': typeof HashtagTagRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/post/$postId': typeof PostPostIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/messages/': typeof MessagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/explore'
    | '/forgot-password'
    | '/home'
    | '/login'
    | '/notifications'
    | '/saved'
    | '/search'
    | '/settings'
    | '/signup'
    | '/hashtag/$tag'
    | '/messages/$conversationId'
    | '/post/$postId'
    | '/profile/$username'
    | '/messages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/explore'
    | '/forgot-password'
    | '/home'
    | '/login'
    | '/notifications'
    | '/saved'
    | '/search'
    | '/settings'
    | '/signup'
    | '/hashtag/$tag'
    | '/messages/$conversationId'
    | '/post/$postId'
    | '/profile/$username'
    | '/messages'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/explore'
    | '/forgot-password'
    | '/home'
    | '/login'
    | '/notifications'
    | '/saved'
    | '/search'
    | '/settings'
    | '/signup'
    | '/hashtag/$tag'
    | '/messages/$conversationId'
    | '/post/$postId'
    | '/profile/$username'
    | '/messages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  ExploreRoute: typeof ExploreRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  HashtagTagRoute: typeof HashtagTagRoute
  MessagesConversationIdRoute: typeof MessagesConversationIdRoute
  PostPostIdRoute: typeof PostPostIdRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hashtag/$tag': {
      id: '/hashtag/$tag'
      path: '/hashtag/$tag'
      fullPath: '/hashtag/$tag'
      preLoaderRoute: typeof HashtagTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$conversationId': {
      id: '/messages/$conversationId'
      path: '/messages/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof MessagesConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$postId': {
      id: '/post/$postId'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof PostPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  ExploreRoute: ExploreRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  HashtagTagRoute: HashtagTagRoute,
  MessagesConversationIdRoute: MessagesConversationIdRoute,
  PostPostIdRoute: PostPostIdRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  MessagesIndexRoute: MessagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
